apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
        - name: llm-api
          image: llm-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
             
---
apiVersion: v1
kind: Service
metadata:
  name: llm-api
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    app: llm-api