apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-api-deployment
  template:
    metadata:
      labels:
        app: qa-api-deployment
    spec:
      containers:
        - name: qa-api
          image: qa-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7777
          env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: database-cluster-app
                  key: pgpass
                  optional: false
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
             
---
apiVersion: v1
kind: Service
metadata:
  name: qa-api
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app: qa-api-deployment